version: '3.9'

name: adonis-boilerplate-docker

# Network
networks:
  adonis_network:
    driver: bridge

services:
  adonis_api:
    container_name: adonis_api
    restart: unless-stopped
    depends_on:
      - mariadb_server
    working_dir: /home/node/app
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
    networks:
      - adonis_network

  # Nginx Web Server
  nginx_server:
    image: nginx:1.17-alpine
    container_name: nginx_server
    restart: unless-stopped
    depends_on:
      - adonis_api
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    networks:
      - adonis_network

  # MySQL Server
  mariadb_server:
    image: mariadb
    container_name: mariadb_server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3309:3306
    networks:
    - adonis_network