version: '3.9'

name: adonis-boilerplate-docker

# Network
networks:
  adonis_network:
    driver: bridge
  
services:
  # Adonisjs App
  adonis_api:
    build: 
      context: .
      dockerfile: custom-docker/Dockerfile
    container_name: adonis_api
    restart: unless-stopped
    depends_on:
      - adonis_mariadb
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - ${PORT}:3333
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    networks:
      - adonis_network

  # Nginx Web Server
  adonis_nginx:
    image: nginx:1.17-alpine
    container_name: adonis_nginx
    restart: unless-stopped
    depends_on:
      - adonis_api
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./custom-docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./custom-docker/nginx/sites-available:/etc/nginx/sites-available
      - ./custom-docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    networks:
      - adonis_network

  # MySQL Server
  adonis_mariadb:
    image: mariadb
    container_name: adonis_mariadb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DB_NAME}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3309:3306
    networks:
    - adonis_network